Fix error handling in Arctualiza

diff --git a/airootfs/Arctine/Tools/Arctualiza/arctualiza b/airootfs/Arctine/Tools/Arctualiza/arctualiza
--- a/airootfs/Arctine/Tools/Arctualiza/arctualiza
+++ b/airootfs/Arctine/Tools/Arctualiza/arctualiza
@@ -44,33 +44,33 @@ upgrade() {
         pushd /OS/arctine-pkg
             echo "11"
             echo "# Discarding any changes made in the source code directory..."
-            git stash || error "Failed to stash commits"
+            git stash || echo "# Failed to stash commits"
             echo "22"
             echo "# Pulling latest commits from OS source..."
-            git pull || error "Failed to pull"
+            git pull || echo "# Failed to pull"
             echo "33"
             echo "# Making sure \"nobody:nobody\" owns the OS source directory..."
-            chown nobody:nobody -Rv . || error "Failed to change ownership to nobody:nobody"
+            chown nobody:nobody -Rv . || echo "# Failed to change ownership to nobody:nobody"
             echo "44"
             echo "# Sourcing PKGBUILD..."
-            source PKGBUILD || error "Failed to source PKGBUILD"
+            source PKGBUILD || echo "# Failed to source PKGBUILD"
             echo "55"
             echo "# Updating all installed packages..."
-            pacman -Syu --noconfirm || error "Failed to update all packages"
+            pacman -Syu --noconfirm || echo "# Failed to update all packages"
             echo "66"
             echo "# Installing all needed dependencies for the update..."
             # shellcheck disable=SC2154
-            pacman -S "${depends[@]}" --noconfirm --needed || error "Failed to install dependencies"
+            pacman -S "${depends[@]}" --noconfirm --needed || echo "# Failed to install dependencies"
             echo "77"
             echo "# Building update package..."
-            sudo -u nobody makepkg -srf || error "Failed to build update package"
+            sudo -u nobody makepkg -srf || echo "# Failed to build update package"
             echo "88"
             echo "# Installing update..."
             # shellcheck disable=SC2154
-            pacman -Uv ./"${pkgname}"-"${pkgver}"-"${pkgrel}"-"${arch[*]}".pkg.tar.zst --noconfirm || error "Failed to install update"
+            pacman -Uv ./"${pkgname}"-"${pkgver}"-"${pkgrel}"-"${arch[*]}".pkg.tar.zst --noconfirm || echo "# Failed to install update"
             echo "99"
             echo "# Finishing up..."
-            chmod +x /Arctine/Tools/ArCLI/Modules/* || error "Failed to add executable flag to ArCLI modules"
+            chmod +x /Arctine/Tools/ArCLI/Modules/* || echo "# Failed to add executable flag to ArCLI modules"
             echo "100"
             echo "# Restarting..."
         popd
